AllCops:
  Exclude:
    - Gemfile
    - lib/**/*.rl
    - lib/racc/grammar_file_scanner.rb
    - tmp/**/*
    - test/regress/**/*

Lint/AssignmentInCondition:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 20
