---
sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem update --remote bundler
install:
  - bundle install --retry 3
script:
  - bundle exec rake test
  - bundle exec rake test_pure
