# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "rdoc", "~>4.0", :group => [:development, :test]
gem "rake", "~>10.4", :group => [:development, :test]
gem "rake-compiler", ">=0.4.1", :group => [:development, :test]
gem "minitest", "~>5.8", :group => [:development, :test]
gem "hoe", "~>3.14", :group => [:development, :test]
gem "hoe-debugging", "~>1.2", :group => [:development, :test]
gem "hoe-doofus", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]

# vim: syntax=ruby
