#
# This file is automatically generated. DO NOT MODIFY!!
#
# raccp.rb
#
#   Copyright (c) 1999-2002 Minero Aoki <aamine@loveruby.net>
#
#   This program is free software.
#   You can distribute/modify this program under the terms of
#   the GNU Lesser General Public License version 2.
#

require 'racc/parser'
require 'racc/raccs'
require 'racc/ucodep'


module Racc

  class GrammarFileParser < Parser

    def initialize( racc )
      @yydebug     = racc.d_parse && Racc_debug_parser
      @ruletable   = racc.ruletable
      @symboltable = racc.symboltable

      @class_name = nil
      @super_class = nil
    end

    attr :class_name
    attr :super_class

    def parse( str )
      @scanner = GrammarFileScanner.new(str)
      @scanner.debug = @yydebug

      do_parse
    end


    private

    def next_token
      @scanner.scan
    end

    def on_error( tok, val, _values )
      if val.respond_to?(:id2name)
        v = val.id2name
      elsif String === val
        v = val
      else
        v = val.inspect
      end
      raise ParseError, "#{@scanner.lineno}: unexpected token '#{v}'"
    end

    STATE_TRANSITION_TABLE

  end

end   # module Racc
