name: test
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'
  push:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.5
  test:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{fromJson(needs.ruby-versions.outputs.versions)}}
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - {os: windows-latest, ruby: truffleruby-head}
          - {os: windows-latest, ruby: truffleruby}
          - {os: windows-latest, ruby: jruby-head}
          - {os: windows-latest, ruby: jruby }
          - {os: macos-latest, ruby: '2.5' }
          - {os: macos-latest, ruby: truffleruby }
          - {os: macos-latest, ruby: truffleruby-head }
          - {os: macos-latest, ruby: jruby }
          - {os: macos-latest, ruby: jruby-head }
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
      if: >-
        startsWith(matrix.ruby, 'jruby')
    - run: bundle install --jobs 4 --retry 3
    - run: rake test
    - run: rake build
